### ISSUE TITLE
Property '_active' does not exist on type 'TooltipModel<keyof ChartTypeRegistry>'

### ISSUE THREAD

**Issue by micobarac** [chartjs/chartjs-plugin-datalabels#273]
With latest version 3.5.1, this code, which worked in 3.5.0, doesn't work anymore:

```javascript
// Create vertical line on hover
export class LineWithLine extends LineController {
  draw() {
    // Call line controller method to draw all the points
    super.draw();

    // Get active tooltip
    const tooltip = this.chart['tooltip'];

    if (tooltip._active && tooltip._active.length) {
      var ctx = this.chart.ctx,
        x = tooltip._active[0].element.x,
        topY = this.chart.scales['y'].top,
        bottomY = this.chart.scales['y'].bottom;

      // Draw vertical line
      ctx.save();
      ctx.setLineDash([1, 1]);
      ctx.beginPath();
      ctx.moveTo(x, topY);
      ctx.lineTo(x, bottomY);
      ctx.lineWidth = 1;
      ctx.strokeStyle = '#424242';
      ctx.stroke();
      ctx.restore();
    }
  }
}
```

How do I get the active tooltip?
